package consts

import "time"

const (
	LIMITS     = 100
	LANGUAGE   = "zh-CN"
	TIMEOUT    = 60 * time.Second
	MAXRETRY   = 3
	EXPIRED    = 7200 * time.Second
	TIMELAYOUT = "2006-01-02 15:04:05"

	//默认值：POSTPAID_BY_HOUR
	INSTANCECHARGETYPE_PREPAID          = "PREPAID"          //包年包月
	INSTANCECHARGETYPE_POSTPAID_BY_HOUR = "POSTPAID_BY_HOUR" //按小时后付费
	INSTANCECHARGETYPE_SPOTPAID         = "SPOTPAID"         //竞价实例

	DISKCHARGETYPE_PREAID           = INSTANCECHARGETYPE_PREPAID
	DISKCHARGETYPE_POSTPAID_BY_HOUR = INSTANCECHARGETYPE_POSTPAID_BY_HOUR
)
